name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install


      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -i github-ec2.pem ${USER}@${HOST}
          cd ~
          # Clone if repo not exists, otherwise pull
          if [ ! -d "my-app" ]; then
            git clone https://github.com/david-diaz-ballastlane/test-repo my-app
          else
            cd my-app
            git pull
          fi

          cd ~/my-app
          npm install
          npm run build
          pm2 delete my-app || true
          pm2 start npm --name "my-app" -- start
